version: '3'
services:
  web:
    build: .
    ports:
      - "5000:3000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./my-finances:/opt/my-finances
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
